services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lms
    ports:
      - "5432:5432" # For db schema migration, wont expose in production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI (development only)
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  local:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
